name: identity_firebase_apple
description: A new Flutter package project.
version: 0.2.0+1
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-apple

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.2.0
  identity: ^0.2.0
  identity_firebase: ^0.2.0
  firebase_auth: ^0.15.3
  apple_sign_in: ^0.1.0

flutter:
  assets:
    - images/apple.png
