name: identity_firebase_apple
description: A Identity Firebase package for Apple provider
version: 0.3.0
homepage: https://github.com/dotronglong/dart-identity-firebase-apple

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  identity: ^0.3.0
  identity_firebase: ^0.3.0
  firebase_auth: ^0.15.3
  apple_sign_in: ^0.1.0

flutter:
  assets:
    - images/apple.png
